### ISSUE TITLE
La aplicación falla al crear una nueva nota

### ISSUE THREAD

**Issue by pinhoscp** [devaigal/nicenotes#1]
La aplicación falla al crear una nueva nota desde la url http://localhost:5000/mkdadmin/new en el momento de pulsar el botón "Save" obteniendo el siguiente error:

FileNotFoundError
FileNotFoundError: [Errno 2] No such file or directory: ''

Traceback (most recent call last)
File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2464, in __call__
return self.wsgi_app(environ, start_response)
File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2450, in wsgi_app
response = self.handle_exception(e)
File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1867, in handle_exception
reraise(exc_type, exc_value, tb)
File "/usr/local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
raise value
File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
response = self.full_dispatch_request()
File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/usr/local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
raise value
File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/app/nicenotes/mkdocsadmin.py", line 252, in submit_new
build_docs()
File "/app/nicenotes/mkdocsadmin.py", line 47, in build_docs
os.chdir(mkddir)
FileNotFoundError: [Errno 2] No such file or directory: ''
The debugger caught an exception in your WSGI application. You can now look at the traceback which led to the error.
To switch between the interactive traceback and the plaintext one, you can click on the "Traceback" headline. From the text traceback you can also create a paste of it. For code execution mouse-over the frame you want to debug and click on the console icon on the right side.

You can execute arbitrary Python code in the stack frames and there are some extra helpers available for introspection:

dump() shows all variables in the frame
dump(obj) dumps all that's known about the object

Se esperaba que al pulsar el botón "Save" guardase los cambios y permitiese continuar con la edición de la nota"

Una vez recargada la aplicación la nota aparece creada.

Entorno: carlosv/python-docker

**Comment by carlos-v** [comment]
El error sucede porque no se ha configurado las rutas de los ejecutables en mkadminconfig.py

Ejemplo:

    MKDOCS_BIN = '/usr/local/bin/mkdocs'
    MKDOCS_DIR = '/Users/carlos/nicenotes'
